# Generated by Django 4.0.3 on 2022-04-07 13:02

import common.validators
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('product_image', models.ImageField(null=True, upload_to='C:\\PycharmProjects\\Python-Web-Framework\\online_shop\\online_shop\\mediafiles\\products\\', validators=[common.validators.MaxFileSizeInMbValidator(5)])),
                ('category', models.CharField(choices=[('----------------', '----------------'), ('Man', 'Man'), ('Woman', 'Woman'), ('Unisex', 'Unisex')], default='----------------', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='Price may not be less than zero!')])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=25, validators=[common.validators.min_length_validator, common.validators.validate_only_letters])),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, validators=[common.validators.min_length_validator, common.validators.validate_only_letters])),
                ('date_of_birth', models.DateField(null=True, validators=[common.validators.MaxDateValidator(datetime.date(2022, 4, 7)), common.validators.MinDateValidator(120)])),
                ('gender', models.CharField(choices=[('Not specified', 'Not specified'), ('Man', 'Man'), ('Woman', 'Woman'), ("Don't want to specify", "Don't want to specify")], default='Not specified', max_length=21)),
                ('address', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('town', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('post_code', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1000, message='Post code should be greater than 999'), django.core.validators.MaxValueValidator(9999, message='Value should not exceed 9999')])),
                ('profile_image', models.ImageField(null=True, upload_to='C:\\PycharmProjects\\Python-Web-Framework\\online_shop\\online_shop\\mediafiles\\profiles\\', validators=[common.validators.MaxFileSizeInMbValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='The quantity can not be less than zero!')])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, validators=[django.core.validators.MinValueValidator(0, message='The quantity can not be less than zero!')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
