# Generated by Django 4.0.3 on 2022-03-28 18:09

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True, validators=[common.validators.age_less_than_zero, common.validators.age_greater_than_120]),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[common.validators.min_length_validator, common.validators.validate_only_letters]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='C:\\PycharmProjects\\Python-Web-Framework\\online_shop\\online_shop/static/images/user.png', upload_to='C:\\PycharmProjects\\Python-Web-Framework\\online_shop\\online_shop/mediafiles/profiles/', validators=[common.validators.MaxFileSizeInMbValidator(5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[common.validators.min_length_validator, common.validators.validate_only_letters]),
        ),
    ]
