# Generated by Django 4.0.3 on 2022-04-08 17:46

import common.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[common.validators.MaxDateValidator(datetime.date(2022, 4, 8)), common.validators.MinDateValidator(120)]),
        ),
    ]
