# Generated by Django 4.0.3 on 2022-03-30 15:08

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='static/images/user.png', upload_to='mediafiles/profiles', validators=[common.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
