# Generated by Django 4.0.3 on 2022-03-30 16:06

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/images/user.png', upload_to='C:\\PycharmProjects\\Python-Web-Framework\\online_shop\\online_shop\\mediafiles\\profiles\\', validators=[common.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
