# Generated by Django 4.0.3 on 2022-04-06 13:26

import common.validators
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_profile_age_profile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('category', models.CharField(choices=[('----------------', '----------------'), ('Man', 'Man'), ('Woman', 'Woman'), ('Unisex', 'Unisex')], default='----------------', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='Price may not be less than zero!')])),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[common.validators.MaxDateValidator(datetime.date(2022, 4, 6)), common.validators.MinDateValidator(120)]),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('quantity', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, validators=[django.core.validators.MinValueValidator(0, message='The quantity can not be less than zero!')])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='The quantity can not be less than zero!')])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.product')),
            ],
        ),
    ]
