# Generated by Django 4.0.3 on 2022-04-06 19:26

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_product_alter_profile_date_of_birth_cart_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='C:\\PycharmProjects\\Python-Web-Framework\\online_shop\\online_shop\\mediafiles\\products\\', validators=[common.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
